version: '3.9'

services:
  frontend:
    build:
      dockerfile: ./apps/frontend/Dockerfile
      context: .
    ports:
      - '3010:4200'
    environment:
      API_URL: http://backend:3333
    depends_on:
      - backend
  backend:
    build:
      dockerfile: ./apps/backend/Dockerfile
      context: .
    ports:
      - '4010:3333'
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/db?schema=public'
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - ./.containers/db:/var/lib/postgresql/data

networks:
  default:
    name: dev_network
    driver: bridge
