version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      dockerfile: ./apps/frontend/Dockerfile
      context: .
    ports:
      - '3010:4200'
    environment:
      API_URL: http://backend:3333
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      dockerfile: ./apps/backend/Dockerfile
      context: .
    ports:
      - '4010:3333'
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/db?schema=public'
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./.containers/redis:/data

networks:
  default:
    name: dev_network
    driver: bridge
